language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"

matrix:
   allow_failures:
      - perl: "5.8"

branches:
    except:
        - "release/cpan"

before_install:
   # git bits sometimes needed...
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'

   # Moose installs in parallel quite nicely.
   - HARNESS_OPTIONS=j8:c cpanm Moose || { cat ~/.cpanm/build.log ; false ; }
   - HARNESS_OPTIONS=j8:c cpanm Dist::Zilla || { cat ~/.cpanm/build.log ; false ; }

   # for DZP LinkCheck
   - cpanm --skip-satisfied CPANPLUS
   - cpanp x

install:
   # not so much install our package as all its prereqs
   - dzil authordeps --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }
   - dzil listdeps --author --missing | cpanm || { cat ~/.cpanm/build.log ; false ; }

script:
   - export DZSIGN=archive
   - dzil test --release --author
