# use the container-based infrastructure
sudo: false

language: perl
perl:
   - "5.24"
   - "5.26"

before_install:
   # git bits sometimes needed...
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'
