language: perl
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"

install:
   # git bits sometimes needed...
   - git config user.name 'Travis-CI'
   - git config user.email 'travis@nowhere.dne'

   # Deal with all of the DZIL dependancies, quickly and quietly
   - cpanm --quiet --notest Dist::Zilla
   - cpanm --verbose --no-interactive --installdeps .
   - dzil authordeps | cpanm --verbose --no-interactive --notest
   # for DZP LinkCheck
   - cpanp x

   - export AUTOMATED_TESTING=1 HARNESS_TIMER=1
   - dzil listdeps | cpanm

script:
   - export DZSIGN=archive
   - dzil smoke --release --author
